package antra.Tictactoe.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AbstractCommand = 0;
  public static final int Board = 1;
  public static final int CommandList = 2;
  public static final int EmptyLine = 3;
  public static final int GameEnded = 4;
  public static final int IfStatement = 5;
  public static final int LogicalExpression = 6;
  public static final int Move = 7;
  public static final int Not = 8;
  public static final int Player = 9;
  public static final int While = 10;
  public static final int isTaken = 11;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xf1d2a8d3b5f04e2aL, 0x8d81e507cb139506L);
    builder.put(0x3dd25694a8251eedL, AbstractCommand);
    builder.put(0x44f073d544acf79aL, Board);
    builder.put(0x3dd25694a8251fb1L, CommandList);
    builder.put(0x1b403d9cecdc9380L, EmptyLine);
    builder.put(0x1b403d9cecea9666L, GameEnded);
    builder.put(0x3022a9353516e2fL, IfStatement);
    builder.put(0x1b403d9cece78fcdL, LogicalExpression);
    builder.put(0x3dd25694a8252b4bL, Move);
    builder.put(0x1b403d9cece78fccL, Not);
    builder.put(0x27111abcbb8099afL, Player);
    builder.put(0x1b403d9cecd851c4L, While);
    builder.put(0x1b403d9cecd1ae8eL, isTaken);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
