package antra.Tictactoe.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilder;
import jetbrains.mps.lang.dataFlow.DataFlowBuilderContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Not_DataFlow extends DataFlowBuilder {
  public void build(final DataFlowBuilderContext _context) {
    _context.getBuilder().emitNop("r:252adb57-d269-4b84-b8d7-a0e84521b9d8(antra.Tictactoe.dataFlow)/1963637181732350537");
    _context.getBuilder().build((SNode) SLinkOperations.getTarget(_context.getNode(), LINKS.original$cffO));
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink original$cffO = MetaAdapterFactory.getContainmentLink(0xf1d2a8d3b5f04e2aL, 0x8d81e507cb139506L, 0x1b403d9cece78fccL, 0x1b403d9cece7c122L, "original");
  }
}
